[package]
name = "memson"
version = "0.1.0"
authors = ["jaupe <jaupe@protonmail.com>"]
edition = "2018"

[dependencies]
bincode = "*"
either = "*"
futures = "0.3"
rayon = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3", features = ["codec"] }
sled = "*"

[dev-dependencies]
assert_approx_eq = "*"