[package]
name = "memson"
version = "0.1.0"
authors = ["jaupe <jaupe@protonmail.com>"]
edition = "2018"

[dependencies]

actix-web = "3"
actix-rt = "*"
env_logger = "*"
serde_json = "*"
serde = { version = "*", features = ["derive"] }

[dev-dependencies]
assert_approx_eq = "*"