[package]
name = "memson"
version = "0.1.0"
authors = ["jaupe <jaupe@protonmail.com>"]
edition = "2018"

[dependencies]
actix-web = "*"
actix-rt = "*"
bincode = "*"
env_logger = "*"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
sled = "*"

[dev-dependencies]
assert_approx_eq = "*"