[package]
name = "memson"
version = "0.1.0"
authors = ["jaupe <jaupe@protonmail.com>"]
edition = "2018"

[[bin]]
name = "memson-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "memson-server"
path = "src/bin/server.rs"

[dependencies]
futures = "*"
rayon = "*"
rustyline = "*"
serde_json = "*"
serde = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["full"] }
yansi = "*"

[dev-dependencies]
assert_approx_eq = "*"