[package]
name = "memson"
version = "0.1.0"
authors = ["jaupe <jaupe@protonmail.com>"]
edition = "2018"

[dependencies]
actix-web = "*"
actix-rt = "*"
bincode = "*"
clap = "*"
env_logger = "*"
serde_json = "*"
serde = { version = "*", features = ["derive"] }
vecmap = "*"

[dev-dependencies]
assert_approx_eq = "*"