[package]
name = "memson"
version = "0.1.0"
authors = ["jaupe <jaupe@protonmail.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
actix = "0.10.0-alpha.3"
actix_derive = "*"
actix-rt = "*"
byteorder = "*"
bytes = "*"
futures-util = "0.3"
rand = "*"
rayon = "*"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sled = "*"
tokio = { version = "0.2", default-features=false, features=["tcp", "time", "signal", "io-util"] }
tokio-util = { version = "0.3", features = ["codec"] }